repos:
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.33.0
  hooks:
  - id: markdownlint

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.4
  hooks:
  - id: codespell

- repo: https://github.com/tcort/markdown-link-check
  rev: v3.10.3
  hooks:
    - id: markdown-link-check
      args: [-q]